version: '3'
services:
  webapp:
    build: .
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - test_network
    volumes:
      - ./logs:/var/log/nginx

networks:
  test_network:
    driver: bridge 